### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by gimlet2** [Kotlin/anko#274]
I've add tabs to my app like following
```  
tabHost {
                relativeLayout {
                    frameLayout {
                        id = android.R.id.tabcontent
                    }
                    tabWidget {
                        id = android.R.id.tabs
                    }
                }
                setup()
                addTab(newTabSpec("Tab1")
                        .setContent {}
                        .setIndicator("Tab1"))
                addTab(newTabSpec("Tab2")
                         .setContent {}
                         .setIndicator("Tab2"))
}
``` 
And my app crashs on lookup of resource with id 0x00.
Then I've replaced tabHost method with following
```
inline fun ViewManager.tabHost1(theme: Int = 0): android.widget.TabHost = tabHost1(theme) {}
inline fun ViewManager.tabHost1(theme: Int = 0, init: android.widget.TabHost.() -> Unit): android.widget.TabHost {
    return ankoView({ ctx: Context -> android.widget.TabHost(ctx, null) }, theme) { init() }
}
```
To call different constructor(TabHost(Context context, AttributeSet attrs)) of TabHost which will initialize mTabLayoutId property but constructor TabHost(Context context) doesn't do that. That would be helpful if you could integrate that.

**Comment by andrejp88** [comment]
I'm having the exact same issue, and having dug through the code a bit I came to the same conclusion. Have you found a solution for this in the meantime?

I think that using a ViewIndicatorStrategy would solve the problem, since it looks like that one does not use the mTabLayoutId property whereas Label/LabelAndIconIndiciatorStrategy do. But it would be much nicer if you could just pass in a string and a drawable instead of creating a custom view for this...

**Comment by gimlet2** [comment]
As you can see in my report - I've created two extension functions - tabHost1 and I'm using them instead original tabHost. I haven't try it for a while. Maybe it is fixed in latest version of Anko.

**Comment by jlberrocal** [comment]
a year later seems is still the same, anko development is very abandoned

**Comment by NeoScript** [comment]
Can confirm, I am also running into this issue, It does seem to be resolved by replacing the tabHost method with the ones from the original post.
