### ISSUE TITLE
android studio 3.0-alpha4 is not supported anko layout preview

### ISSUE THREAD

**Issue by tjt852** [Kotlin/anko#421]
My android studio 3.0-alpha4 is not supported
auko library and plugins version 0.10.1
![image](https://user-images.githubusercontent.com/5794936/27471591-d1b701a0-582a-11e7-9d0b-e3edfd0d00a0.png)

**Comment by JamesKarl** [comment]
I have the  same issue.

**Comment by benluo** [comment]
It does not only preview, but does not render in programm neither.

**Comment by benluo** [comment]
it shows blank in android phone or in emulator.

**Comment by tjt852** [comment]
@benluo Running on the phone no problem, that is, can not preview

**Comment by benluo** [comment]
I cannot show in the phone (n5, android 6.0) either.

**Comment by JoeMaher** [comment]
Im see the same issue, easily replicated with

    class StartActivity: AppCompatActivity() {

        override fun onCreate(savedInstanceState: Bundle?) {
            super.onCreate(savedInstanceState)
            StartLayout().setContentView(this)
        }
    }

    class StartLayout: AnkoComponent<StartActivity> {

        override fun createView(ui: AnkoContext<StartActivity>): View {
            return with(ui) {
                linearLayout {
                    lparams(width = matchParent, height = matchParent)
                    backgroundColor = ContextCompat.getColor(ctx, R.color.darkBlue)
                }
            }
        }
    }

**Comment by elton2048** [comment]
In Android Studio 3.0-alpha 5 (Canary 5) the issue still exists. There is no preview item to be selected.

**Comment by benluo** [comment]
same behavor. It shows blank in real phone (n5 with Android 6).

**Comment by JoeMaher** [comment]
@elton2048 and @benluo make sure your appcompat dependency is `com.android.support:appcompat-v7:26.0.0-beta1`

**Comment by benluo** [comment]
I tried again after change the dependency. But nothing changed. Anko layout does not work in real phone.

`import org.jetbrains.anko.*
import org.jetbrains.anko.sdk25.coroutines.onClick

class SignInActivityUI : AnkoComponent<SignInActivity> {
    override fun createView(ui: AnkoContext<SignInActivity>) = with(ui) {
        verticalLayout {
            val textView = textView()
            textView.text = "hello"
            val workingNo = editText {
                hintResource = R.string.working_no
            }
            val password = editText()
            password.hint = R.string.password.toString()
            button(R.string.title_activity_login) {
                onClick { ctx.toast("Hello")}//, ${workingNo.text}!") }
            }
        }
    }
}`

**Comment by kirillkh** [comment]
The menu option "Anko Layout Preview" is greyed out for me.

**Comment by benluo** [comment]
I have the same problem.

**Comment by a1018875550** [comment]
I have the same problem.

**Comment by Aheadboy** [comment]
i have already install the plugin,and extend the AnkoComponent interface.but there is nothing show for me.event not show grey "anko layout preview".am i find wrong place?where you gays
find "anko layout preview" .my android studio is 3.0,  canary 8.
hope solve this  as quick as possible

**Comment by etsit** [comment]
The "Anko Layout Preview" option is not visible at all on the "Views -> Tool Windows" menu
in *Android Studio 3.0 Beta 1* (MacOS Sierra)
I'm first putting the cursor in my "view declaration" (my AnkoComponent<MainActivity>) implementation according to https://github.com/Kotlin/anko/wiki/Anko-Layouts#using-the-plugin

**Comment by vafu** [comment]
same on 3.0 beta2

**Comment by a1018875550** [comment]
see the wiki  https://github.com/Kotlin/anko/wiki/Anko-Layouts#using-the-plugin ; it's not yet support android studio 3.0+

**Comment by kirillkh** [comment]
Actually, it says "supported only in Android Studio 2.4+". The version 3.0 matches that requirement.

**Comment by vafu** [comment]
anyway, xml -> anko convertion works, so plugin works too, I just can't get the preview

**Comment by Edward608** [comment]
Still no preview in AS 3.0 beta 4

**Comment by vafu** [comment]
come on, JetBrains, Google told you that anko is not the right way and you discontinued the library ?

**Comment by Edward608** [comment]
When did google talked about anko? Can someone give me the source of reference?

**Comment by tyzero** [comment]
Still no preview in AS 3.0 beta 6

**Comment by AweiLoveAndroid** [comment]
啥时候出正式版

**Comment by ShyamAg** [comment]
Just Change the theme "AppTheme"  to NoTitleBar

**Comment by duymon178** [comment]
The only solution now is to rebuild your project to see any changes.

**Comment by 4u7** [comment]
Fixed with c685e07256673f144d788c51865c6a42e13da120

**Comment by JacobAMason** [comment]
I still see this error on Anko 0.10.4 with Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.13-1-ARCH

I'm including Anko in my module's build.gradle as 
```gradle
dependencies {
    ...
    implementation "org.jetbrains.anko:anko:$anko_version"
    ...
}
```
and my code seems to build okay, however the preview causes the java process running Android Studio to spike the CPU.

**Comment by iammiles** [comment]
I just started a new project today using minSdk of 25 and I'm getting the same issue with the example verticalLayout.
